name: black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: psf/black@stable
        with:
          options: "--check --diff --verbose"
          src: "resman.py"
